# Generated by Django 5.2.5 on 2025-08-23 12:33

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Ghanaian phone number (e.g., +233201234567 or 0201234567)",
                                regex="^(\\+233|0)(20|23|24|26|27|28|50|53|54|55|56|57|59)\\d{7}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("other_names", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("greater_accra", "Greater Accra"),
                            ("ashanti", "Ashanti"),
                            ("western", "Western"),
                            ("central", "Central"),
                            ("volta", "Volta"),
                            ("eastern", "Eastern"),
                            ("northern", "Northern"),
                            ("upper_east", "Upper East"),
                            ("upper_west", "Upper West"),
                            ("brong_ahafo", "Brong Ahafo"),
                            ("western_north", "Western North"),
                            ("ahafo", "Ahafo"),
                            ("bono_east", "Bono East"),
                            ("oti", "Oti"),
                            ("north_east", "North East"),
                            ("savannah", "Savannah"),
                        ],
                        max_length=20,
                    ),
                ),
                ("city_town", models.CharField(max_length=100)),
                ("area_suburb", models.CharField(blank=True, max_length=100)),
                ("emergency_contact_name", models.CharField(max_length=200)),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Ghanaian phone number",
                                regex="^(\\+233|0)(20|23|24|26|27|28|50|53|54|55|56|57|59)\\d{7}$",
                            )
                        ],
                    ),
                ),
                ("emergency_contact_relationship", models.CharField(max_length=50)),
                ("sms_notifications", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=False)),
                ("whatsapp_notifications", models.BooleanField(default=True)),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "clients",
            },
        ),
    ]
